ALTER TABLE customers ADD COLUMN IF NOT EXISTS total_turnover NUMERIC(14, 2) DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS invoice_count INT DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS total_hours NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS contract_value NUMERIC(14, 2) DEFAULT 0;
