ALTER TABLE customer_kpis
  ADD COLUMN IF NOT EXISTS customer_hours NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS absence_hours NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS internal_hours NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_hours NUMERIC(10, 2) NOT NULL DEFAULT 0;
